services:
  - type: web
    name: md-store-test
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: md-store-test-db
          property: connectionString
      - key: PGSSL
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: STORE_NAME
        value: M&D Store
      - key: PUBLIC_URL
        value: https://md-store-test.onrender.com
      - key: CURRENCY
        value: TND
      - key: WHATSAPP
        value: "21600000000"

databases:
  - name: md-store-test-db
    databaseName: md_store
    user: md_store
    plan: free
    region: frankfurt
    ipAllowList: []
